class Dummy {
  Future<String> getDummies() {
    return Future.delayed(const Duration(milliseconds: 2000), () {
      return ("""
    {
    "GENRESTRT": [
        {
            "head": [
                {
                    "list_total_count": 28472
                },
                {
                    "RESULT": {
                        "CODE": "INFO-000",
                        "MESSAGE": "정상 처리되었습니다."
                    }
                },
                {
                    "api_version": "1.0"
                }
            ]
        },
        {
            "row": [
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3188140",
                    "MANAGE_NO": "5560000-101-1994-00064",
                    "LICENSG_DE": "19940224",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "02",
                    "UNITY_BSN_STATE_DIV_CD": "03",
                    "UNITY_BSN_STATE_NM": "폐업",
                    "BSN_STATE_NM": "폐업",
                    "CLSBIZ_DE": "20150508",
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": "031 4139312",
                    "LOCPLC_AR_INFO": "50.49",
                    "BIZPLC_NM": "24시감자탕",
                    "BIZCOND_DIV_NM_INFO": "한식",
                    "X_CRDNT_VL": "184631.278132542",
                    "Y_CRDNT_VL": "424112.45899488",
                    "SANITTN_BIZCOND_NM": "한식",
                    "MALE_ENFLPSN_CNT": 0,
                    "FEMALE_ENFLPSN_CNT": 0,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": 0,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": 0,
                    "FACTRY_SALE_DUT_EMPLY_CNT": 0,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": 0,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": 0,
                    "MTRENT_AMT": 0,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "50.49",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 고잔동 520-4번지",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 단원구 원고잔로 15, 1층 (고잔동,  반월빌딩 113,114호)",
                    "REFINE_ZIP_CD": "15357",
                    "REFINE_WGS84_LOGT": "126.8273516",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3296697",
                    "MANAGE_NO": "5560000-101-2012-00105",
                    "LICENSG_DE": "20120418",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "02",
                    "UNITY_BSN_STATE_DIV_CD": "03",
                    "UNITY_BSN_STATE_NM": "폐업",
                    "BSN_STATE_NM": "폐업",
                    "CLSBIZ_DE": "20151002",
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": null,
                    "LOCPLC_AR_INFO": "63.35",
                    "BIZPLC_NM": "시골팥칼국수",
                    "BIZCOND_DIV_NM_INFO": "한식",
                    "X_CRDNT_VL": "185646.270143408",
                    "Y_CRDNT_VL": "425316.475176351",
                    "SANITTN_BIZCOND_NM": "한식",
                    "MALE_ENFLPSN_CNT": null,
                    "FEMALE_ENFLPSN_CNT": null,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": null,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": null,
                    "FACTRY_SALE_DUT_EMPLY_CNT": null,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": null,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": null,
                    "MTRENT_AMT": null,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "63.35",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 고잔동 646-17번지 1층 일부 101호",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 단원구 예술대학로 146, 1층 101호 (고잔동, 1층 일부)",
                    "REFINE_ZIP_CD": "15261",
                    "REFINE_WGS84_LOGT": "126.8388014",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3395018",
                    "MANAGE_NO": "5560000-101-2001-01769",
                    "LICENSG_DE": "20011119",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "01",
                    "UNITY_BSN_STATE_DIV_CD": "01",
                    "UNITY_BSN_STATE_NM": "영업/정상",
                    "BSN_STATE_NM": "영업",
                    "CLSBIZ_DE": null,
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": "031 4054832",
                    "LOCPLC_AR_INFO": null,
                    "BIZPLC_NM": "갈비나라",
                    "BIZCOND_DIV_NM_INFO": "식육(숯불구이)",
                    "X_CRDNT_VL": "184662.19991704",
                    "Y_CRDNT_VL": "426410.711365774",
                    "SANITTN_BIZCOND_NM": "식육(숯불구이)",
                    "MALE_ENFLPSN_CNT": 0,
                    "FEMALE_ENFLPSN_CNT": 0,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": null,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": null,
                    "FACTRY_SALE_DUT_EMPLY_CNT": null,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": null,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": null,
                    "MTRENT_AMT": null,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "0",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 와동 119-1번지 1층",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 단원구 와동로 106 (와동, 119-1  1층)",
                    "REFINE_ZIP_CD": "15255",
                    "REFINE_WGS84_LOGT": "126.8276646",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3258581",
                    "MANAGE_NO": "5560000-101-1998-00462",
                    "LICENSG_DE": "19980622",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "02",
                    "UNITY_BSN_STATE_DIV_CD": "03",
                    "UNITY_BSN_STATE_NM": "폐업",
                    "BSN_STATE_NM": "폐업",
                    "CLSBIZ_DE": "20030523",
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": "493-3800",
                    "LOCPLC_AR_INFO": "104.28",
                    "BIZPLC_NM": "주점노다지",
                    "BIZCOND_DIV_NM_INFO": "한식",
                    "X_CRDNT_VL": null,
                    "Y_CRDNT_VL": null,
                    "SANITTN_BIZCOND_NM": "한식",
                    "MALE_ENFLPSN_CNT": 0,
                    "FEMALE_ENFLPSN_CNT": 0,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": 0,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": 0,
                    "FACTRY_SALE_DUT_EMPLY_CNT": 0,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": 0,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": 0,
                    "MTRENT_AMT": 0,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "104.28",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 원곡동 828번지 2단지복합상가 1층 108.109.110호",
                    "REFINE_ROADNM_ADDR": null,
                    "REFINE_ZIP_CD": null,
                    "REFINE_WGS84_LOGT": "126.7981922",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3178682",
                    "MANAGE_NO": "5560000-101-1991-00063",
                    "LICENSG_DE": "19910315",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "02",
                    "UNITY_BSN_STATE_DIV_CD": "03",
                    "UNITY_BSN_STATE_NM": "폐업",
                    "BSN_STATE_NM": "폐업",
                    "CLSBIZ_DE": "19941209",
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": null,
                    "LOCPLC_AR_INFO": ".00",
                    "BIZPLC_NM": "성지식당",
                    "BIZCOND_DIV_NM_INFO": "한식",
                    "X_CRDNT_VL": "185198.772560562",
                    "Y_CRDNT_VL": "424006.292478327",
                    "SANITTN_BIZCOND_NM": "한식",
                    "MALE_ENFLPSN_CNT": 0,
                    "FEMALE_ENFLPSN_CNT": 0,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": 0,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": 0,
                    "FACTRY_SALE_DUT_EMPLY_CNT": 0,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": 0,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": 0,
                    "MTRENT_AMT": 0,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "0",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 고잔동 536-1번지 1층3호",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 단원구 당곡로 10 1층 3호 (고잔동)",
                    "REFINE_ZIP_CD": "15360",
                    "REFINE_WGS84_LOGT": "126.8337729",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3308115",
                    "MANAGE_NO": "5560000-101-2016-00186",
                    "LICENSG_DE": "20160809",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "01",
                    "UNITY_BSN_STATE_DIV_CD": "01",
                    "UNITY_BSN_STATE_NM": "영업/정상",
                    "BSN_STATE_NM": "영업",
                    "CLSBIZ_DE": null,
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": null,
                    "LOCPLC_AR_INFO": "111.36",
                    "BIZPLC_NM": "스테이(stay)",
                    "BIZCOND_DIV_NM_INFO": "호프/통닭",
                    "X_CRDNT_VL": "181037.727297625",
                    "Y_CRDNT_VL": "425451.54445531",
                    "SANITTN_BIZCOND_NM": "호프/통닭",
                    "MALE_ENFLPSN_CNT": null,
                    "FEMALE_ENFLPSN_CNT": null,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": null,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": null,
                    "FACTRY_SALE_DUT_EMPLY_CNT": null,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": null,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": null,
                    "MTRENT_AMT": null,
                    "MULTI_USE_BIZESTBL_YN": "Y",
                    "FACLT_TOT_SCALE_INFO": "111.36",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 신길동 1612번지 한중빌딩 201호",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 단원구 신길로 8, 201호 (신길동, 한중빌딩)",
                    "REFINE_ZIP_CD": "15402",
                    "REFINE_WGS84_LOGT": "126.7867712",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3447279",
                    "MANAGE_NO": "5560000-101-2016-00111",
                    "LICENSG_DE": "20160510",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "02",
                    "UNITY_BSN_STATE_DIV_CD": "03",
                    "UNITY_BSN_STATE_NM": "폐업",
                    "BSN_STATE_NM": "폐업",
                    "CLSBIZ_DE": "20180601",
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": null,
                    "LOCPLC_AR_INFO": "35.35",
                    "BIZPLC_NM": "와리포차",
                    "BIZCOND_DIV_NM_INFO": "분식",
                    "X_CRDNT_VL": "184145.255780046",
                    "Y_CRDNT_VL": "426988.327647095",
                    "SANITTN_BIZCOND_NM": "분식",
                    "MALE_ENFLPSN_CNT": null,
                    "FEMALE_ENFLPSN_CNT": null,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": null,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": null,
                    "FACTRY_SALE_DUT_EMPLY_CNT": null,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": null,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": null,
                    "MTRENT_AMT": null,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "35.35",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 와동 779-4번지 1층 102호",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 단원구 와동공원로8길 12, 102호 (와동)",
                    "REFINE_ZIP_CD": "15250",
                    "REFINE_WGS84_LOGT": "126.8218291",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3146697",
                    "MANAGE_NO": "5550000-101-2002-00903",
                    "LICENSG_DE": "20020605",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "02",
                    "UNITY_BSN_STATE_DIV_CD": "03",
                    "UNITY_BSN_STATE_NM": "폐업",
                    "BSN_STATE_NM": "폐업",
                    "CLSBIZ_DE": "20030210",
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": "031 4067758",
                    "LOCPLC_AR_INFO": "30.60",
                    "BIZPLC_NM": "연풍연가호프",
                    "BIZCOND_DIV_NM_INFO": "호프/통닭",
                    "X_CRDNT_VL": "187638.416633595",
                    "Y_CRDNT_VL": "423649.939542063",
                    "SANITTN_BIZCOND_NM": "호프/통닭",
                    "MALE_ENFLPSN_CNT": 0,
                    "FEMALE_ENFLPSN_CNT": 0,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": null,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": null,
                    "FACTRY_SALE_DUT_EMPLY_CNT": null,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": null,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": null,
                    "MTRENT_AMT": null,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "30.6",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 상록구 일동 568-5번지 1층",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 상록구 식물원로 3 1층 (일동)",
                    "REFINE_ZIP_CD": "15321",
                    "REFINE_WGS84_LOGT": "126.8612944",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.2579269",
                    "MANAGE_NO": "3930000-101-2016-00018",
                    "LICENSG_DE": "20161014",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "02",
                    "UNITY_BSN_STATE_DIV_CD": "03",
                    "UNITY_BSN_STATE_NM": "폐업",
                    "BSN_STATE_NM": "폐업",
                    "CLSBIZ_DE": "20180813",
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": "032 880 9760",
                    "LOCPLC_AR_INFO": "130.40",
                    "BIZPLC_NM": "대부만남의광장",
                    "BIZCOND_DIV_NM_INFO": "한식",
                    "X_CRDNT_VL": "163088.623978709",
                    "Y_CRDNT_VL": "417422.736364945",
                    "SANITTN_BIZCOND_NM": "한식",
                    "MALE_ENFLPSN_CNT": null,
                    "FEMALE_ENFLPSN_CNT": null,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": null,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": null,
                    "FACTRY_SALE_DUT_EMPLY_CNT": null,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": null,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": null,
                    "MTRENT_AMT": null,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "130.4",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 대부북동 38-7번지 1층 일부",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 단원구 뻐꾹산길 126-11, 1층 (대부북동, 일부)",
                    "REFINE_ZIP_CD": "15640",
                    "REFINE_WGS84_LOGT": "126.5846614",
                    "SIGUN_NM": "안산시"
                },
                {
                    "SIGUN_CD": "41270",
                    "REFINE_WGS84_LAT": "37.3311738",
                    "MANAGE_NO": "5560000-101-2001-01599",
                    "LICENSG_DE": "20011010",
                    "LICENSG_CANCL_DE": null,
                    "BSN_STATE_DIV_CD": "02",
                    "UNITY_BSN_STATE_DIV_CD": "03",
                    "UNITY_BSN_STATE_NM": "폐업",
                    "BSN_STATE_NM": "폐업",
                    "CLSBIZ_DE": "20040906",
                    "SUSPNBIZ_BEGIN_DE": null,
                    "SUSPNBIZ_END_DE": null,
                    "REOPENBIZ_DE": null,
                    "LOCPLC_FACLT_TELNO": "031 4952208",
                    "LOCPLC_AR_INFO": "25.32",
                    "BIZPLC_NM": "풍천장어",
                    "BIZCOND_DIV_NM_INFO": "기타",
                    "X_CRDNT_VL": "181573.333453045",
                    "Y_CRDNT_VL": "425491.039257206",
                    "SANITTN_BIZCOND_NM": "기타",
                    "MALE_ENFLPSN_CNT": 0,
                    "FEMALE_ENFLPSN_CNT": 0,
                    "BSNSITE_CIRCUMFR_DIV_NM": null,
                    "GRAD_DIV_NM": null,
                    "GRAD_FACLT_DIV_NM": null,
                    "TOT_EMPLY_CNT": null,
                    "HEADOFC_EMPLY_CNT": null,
                    "FACTRY_OFCRK_DUT_EMPLY_CNT": null,
                    "FACTRY_SALE_DUT_EMPLY_CNT": null,
                    "FACTRY_PRODCTN_DUT_EMPLY_CNT": null,
                    "BULDNG_POSESN_DIV_NM": null,
                    "ASSURNC_AMT": null,
                    "MTRENT_AMT": null,
                    "MULTI_USE_BIZESTBL_YN": "N",
                    "FACLT_TOT_SCALE_INFO": "25.32",
                    "TRADITN_BIZESTBL_APPONT_NO": null,
                    "TRADITN_BIZESTBL_CHIEF_FOOD_NM": null,
                    "HMPG_URL": null,
                    "REFINE_LOTNO_ADDR": "경기도 안산시 단원구 원곡동 748-4번지 1층",
                    "REFINE_ROADNM_ADDR": "경기도 안산시 단원구 원본로1길 10-14 1층 (원곡동)",
                    "REFINE_ZIP_CD": "15378",
                    "REFINE_WGS84_LOGT": "126.7928294",
                    "SIGUN_NM": "안산시"
                }
            ]
        }
    ]
}
""");
    });
  }
}
